-- ### WIP ###
WITH highlights AS (
  SELECT "" as name, "" as shortname, 0 as highlight
  UNION ALL SELECT "AMERICAN STOCK TRANSFER & TRUST COMPANY, LLC", "AST", 1
  UNION ALL SELECT "AMERICAN STOCK TRANSFER & TRUST COMPANY, LLC/AST2", "AST 2", NULL
  UNION ALL SELECT "EQUINITI TRUST COMPANY", "Equiniti", 1
  UNION ALL SELECT "EQUINITI TRUST COMPANY/MICRO CAP", "Equiniti Microcap", NULL
  UNION ALL SELECT "BROADRIDGE CORPORATE ISSUER SOLUTIONS INC." 

)
SELECT 
        pk1_dtcMemberId as id,
        name,
        REGEXP_EXTRACT()
